### ISSUE TITLE
Use your tool in my blog - any suggest for edit

### ISSUE THREAD

**Issue by vanloc0301** [repeats/Repeat#17]
Hi @hptruong93 
I use your tool on my blog at here: [https://sharengay.com/tool-automation-tu-dong-hoa-moi-cong-viec-that-de-dang/](https://sharengay.com/tool-automation-tu-dong-hoa-moi-cong-viec-that-de-dang/)
The language in my blog is Vietnamese. I think you also read and understand.
Hope you can suggestions for missing anything in my post?
I expected with your tool. I hope many people know your repository.

**Comment by hptruong93** [comment]
Hi,
Thanks for the blogpost. This looks really good.
Didn't expect to have someone write about this in a blogpost.

Just want to point out that since the code you're writing is Java, you can read file from local disk using various libraries available in Java. For example, Excel files can be read from and written to using Apache POI (https://poi.apache.org/).

Best,
HP

**Comment by vanloc0301** [comment]
Thank @hptruong93 . I will don't add this feature to my blog because this hard for the beginner user.
Thanks for your response.
