### ISSUE TITLE
How to record scroll mouse?

### ISSUE THREAD

**Issue by vanloc0301** [repeats/Repeat#4]
Repeat seem only saves mouse position and a keyboard event.

Have any method to also keep record scroll mouse or select the paragraph in webpage(hold left mouse)?

Thanks.

**Comment by hptruong93** [comment]
For scrolling: I don't want to include mouse due to intricacies in dealing with scrolling speed. The underlying implementation Robot.java (see https://docs.oracle.com/javase/7/docs/api/java/awt/Robot.html) will have different scrolling speed from the system's scrolling speed. In addition, for scrolling down, you can just press the down button on the keyboard right?

For holding mouse, recording is unreliable due to the underlying JNativeHook generating odd events in case of a mouse drag. For precise control of the mouse, I suggest writing up the task manually using mouse controller API.

**Comment by vanloc0301** [comment]
Great explain. 

In any case, you can't use navigation key to control. 

Like:
Insert data to a `Textbox` on the web, still using `TAB` key go to next.
Other issues will appear.

Thanks @hptruong93 .

**Comment by hptruong93** [comment]
It really boils down to what you can do without the scroll wheel on the mouse. The workaround is for every task that you use the mouse wheel to scroll, imagine how you can do the same task if you didn't have the scroll wheel on the mouse in the first place.
I do agree that it is much more inconvenient for us to use a mouse without the scroll wheel, but the computer wouldn't mind repeating the task once we've successfully recorded it.
